config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :appointments
  root "appointments#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :user
    belongs_to :doctors
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :appointments
    has_many :users, through: :appointments
end

app/models/user.rb
class User < ApplicationRecord
    has_many :doctors
    has_many :doctors, through: :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

    def index
        @appointments = Appointment.all.order("date ASC")
    end

    def new
        @appointment = Appointment.new
    end

    def create
        @appointment = Appointment.new(appointment_params)

        if @appointment.save
            redirect_to @appointment
        else
            render 'new'
        end
    end

    def show
        @appointment = Appointment.find(params[:id])
    end

    def update
        @appointment = Appointment.find(params[:id])

        if @appointment.update(appointment_params)
            redirect_to @appointment
        else
            render 'edit'
        end
    end

    def edit
        @appointment = Appointment.find(params[:id])
    end

    def destroy
        @appointment = Appointment.find(params[:id])
        @appointment.destroy


        redirect_to appointments_path
    end

    private

    def appointment_params
        params.require(:appointment).permit(:appointment_type, :date, :time, :notes)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/_form.html.erb
<div class="section">
<%= simple_form_for @appointment do |f| %>
    <div class="field">
        <div class="control">
            <%= f.input :appointment_type, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label'} %>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <%= f.input :date, input_html: { class: 'date' }, wrapper: false, label_html: { class: 'label'} %>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <%= f.input :time, input_html: { class: 'time' }, wrapper: false, label_html: { class: 'label'} %>
        </div>
    </div>

    <div class="field">
         <div class="control">
            <%= f.input :notes, input_html: { class: 'typearea' }, wrapper: false, label_html: { class: 'label'} %>
        </div>
    </div>
    <%= f.button :submit, class: "button is-primary" %>
<% end %>
</div>

app/views/appointments/edit.html.erb
<% content_for :page_title, "Edit Appointment" %> 

<%= render 'form' %>

app/views/appointments/index.html.erb
<% content_for :page_title, "All Appointments" %>

<section class="section"
    <div class="container">
        <% @appointments.each do |appointment| %>
            <div class="card">
                <div class="card-content">
                    <div class="media">
                        <div class="media-content">
                            <p class="Appointment #"><%= link_to appointment.date, appointment %></p>
                        </div>
                    </div>
                    <div class="appointment-type">
                        <%= appointment.appointment_type %>
                    </div>
                    <div class="time">
                        <%= appointment.time %>
                    </div>
                    <div class="notes">
                        <%= appointment.notes %>
                    </div>
                </div>
            </div>
        <% end %>          
    </div>
</section>

app/views/appointments/new.html.erb
<% content_for :page_title, "New Appointment" %>

<%= render 'form' %>

app/views/appointments/show.html.erb
<% content_for :page_title, @appointment.date %> 

<section class="section">
	<div class="container">
		<nav class="level">
		  <!-- Left side -->
		  <div class="level-left">
		    <p class="level-item">
		        <strong>Actions</strong>
		    </p>
		  </div>
		  <!-- Right side -->
		  <div class="level-right">
		  	<p class="level-item">
		    	<%= link_to "Edit", edit_appointment_path(@appointment), class:"button" %>
		  	</p>
		  	<p class="level-item">
				<%= link_to "Delete", appointment_path(@appointment), method: :delete, data: { confirm: "Are you sure?" }, class:"button is-danger" %>
				</p>
		  </div>
		</nav>
		<hr/>

        <div class="date">
			<h1> <%= @appointment.date %> </h1>
		</div>
        <div class="appointment_type">
			<%= @appointment.appointment_type %>
		</div>
        <div class="time">
			<%= @appointment.time %>
		</div>
        <div class="notes"> Notes:
			<%= @appointment.notes %>
		</div>
	</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalenDOC</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<section class="hero is-primary is-medium">
	  <!-- Hero head: will stick at the top -->
	  <div class="hero-head">
	    <nav class="navbar">
	      <div class="container">
	        <div class="navbar-brand">
	          <%= link_to 'CalenDOC', root_path, class: "navbar-item" %>
	          <span class="navbar-burger burger" data-target="navbarMenuHeroA">
	            <span></span>
	            <span></span>
	            <span></span>
	          </span>
	        </div>
	        <div id="navbarMenuHeroA" class="navbar-menu">
	          <div class="navbar-end">
	            <%= link_to "Create New Appointment", new_appointment_path, class:"navbar-item" %>
	          </div>
	        </div>
	      </div>
	    </nav>
	  </div>

	  <!-- Hero content: will be in the middle -->
	  <div class="hero-body">
	    <div class="container has-text-centered">
	      <h1 class="title">
	        <%= yield :page_title %>
	      </h1>
	    </div>
	  </div>
	</section>
    <%= yield %>
  </body>
</html>